#+TITLE:       Exporting pets from Saudi Arabia to Europe
#+AUTHOR:      Heikki Lehvaslaiho
#+EMAIL:       heikki.lehvaslaiho@gmail.com
#+DATE:        2015-02-23 Mon
#+URI:         /blog/%y/%m/%d/exporting-pets-from-saudi-arabia-to-europe
#+KEYWORDS:    Saudi Arabia, pet export
#+TAGS:        saudi
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Pet export details

I describe here the steps I took to transport dogs out of Saudi Arabia
to Finland on two different occasions in the past 7 months. Note that
regulations change frequently so do check the details again before
your flight to learn about new developments.

* General

The vet has to fill in the *EU Vet Health Certificate* (Form 998). It
has to in the official format: four A4 pages printed on one folded A3.

The EU regulations state that the health certificate has to be 1 to 10
days old at time of entry to EU. Exceptions at the moment are UK,
Finland, and Malta that allow the certificate to be only 1 to 5 days
old. Note that other European countries may have additional
requirements for importation.

The most important topic in your dogs health record is the *rabies
vaccination*. It has to have been continuously valid since the rabies
titer test proved that the dog has enough antibodies against rabies
bacteria. Saudi Arabia requires annual rabies revaccinations. If there
is a lapse in this schedule, the titer test needs to be redone and the
dog can travel only after three months has passed from the positive
result.

Saudi Arabia requires an *export permit* for live animals. It should
not be older than seven days at time of departure. (The vet told me it
has to be exactly 7 days, but at ministry they were even suggesting
coming back in a couple of days to avoid running over.)

The best airline to transport dogs out of Saudi Arabia is *Lufthansa*.
It is the only one that takes live animals as excess luggage. Others
take them as cargo which makes the transport a lot more complicated.
Also, Lufthansa has the Europe's best animal facility at Frankfurt
Airport. Lufthansa has reasonable (compared to other airlines) fixed
rates. I paid 780 SAR for a small dog and 1510 SAR for a medium dog.

At the time of booking your Lufthansa flight, or right after you have
received your ticket from a travel agency, call Lufthansa Customer
Care and *reserve a place for your animal*. One plane can take only two
animals at the time and if they are both dogs, they must both be
yours. You do not pay anything at this point (and annoyingly, your
updated flight reservation still does not show the reserved animal
place. You have to trust Lufhansa on that.)

* Saudi Arabian Export Permit

I dealt with [[http://www.eurovetclinic.com/][Eurovets]] in Jeddah. They charge a normal consultation fee
for the health certificate, and if you need their driver to lead you
to the *Agriculture Ministry*, the charge for that is 300 SAR. The
Ministry is in South-Eastern Jeddah along Old Mecca Road close to the
junction to the Jeddah Ring Road. I have prepared a route map for the
[[https://www.google.com/maps/d/edit?mid=z7XEAJwA5Bkk.kx5hm2ijgHJE][fastest route there from EuroVets (link)]] as it is not a
straightforward route. Note that I could not correctly draw the end of
the route on Google map due to a missing road connection. You need to
drive east on Old Mekkah Road, past the Ministry, do a U-turn, and
take immediately the service road to the Ministry entrance.

You need to be at EuroVets at 9 AM to be at the ministry well before
noon. The vet will inspect the dog, give the deworming injections,
write a health certificate for the Ministry, and fill in the EU
certificate. In my case I had to come back to Eurovets a couple of
days later for the injections and the EU certificate because of the
Finnish regulations mentioned above.

The ministry is in a compound with a guard. You'll have no trouble
getting in once the guard has seen the animal in your car. The
entrance to export permit offices is in the far corner of the
first building on your right. Park you car outside the offices (there
is limited shaded parking, but leave you car running in the summer) and
leave the dog in the car. The dog has to be there in the remote chance
someone might actually want to see him. If you are exporting a cat,
you'll have to bring her in.

Go in past the first reception on your left to the end of the short
corridor and up a couple of steps. The vet in charge has office on
your left. (In his absence you might have to deal with other people in
offices you went past.) He will check the papers: Your iqama, (and
your passport), the health certificate, and the pet passport. Only a
person with iqama can get the export permit, but you can assign the
transport rights to another person who will accompany the animal.
That person needs to be present at the ministry.

The vet will write instructions that you take to the first reception
where they will print the export permit in triplicate. The vet and you
will sign the master copy, and then you will take them all to the second
reception that you will find on your left after walking for about 30
meters along the corridor that leads right from the entrance corridor.

At the second reception they will add more signatures and give you
back the master copy of the export permit. The permit is free of
charge.

* Preparing for the flight

To prepare for the flight, take paper *copies* of the following
documents:

- your passport
- Saudi export permit
- 2 copies of the EU Health certificate
- pet passport, all relevant pages

Tape a transparent plastic *folder* on the crate with:

- a copy of the Saudi Export permit
- a copy of the pet passport
- the original EU health certificate

Prepare the crate with bedding and a water and a food cup attached to
the inside of the door (One cup for water is good enough for short
flights to Europe). Weigh the crate and the dog. You'll need the
*total weight* at the airport. Take all the other papers with you in
the hand luggage. Take *a leash and a collar* for the animal with you.

* At the airport

Go straight to Lufthansa counter at North Terminal. You will check in,
fill in a sticker with your contact details and particular needs of the
animal, and pay the fee. Place the sticker visibly on the crate.

Keep the crate on a trolly and a Lufthansa employee will guide you
through a locked door at end of the hall to a scanning area. The
Lufthansa person will fill in the customs form for you. The customs
officer will take it and the copy of the export permit from the
crate. You'll need the leash to take the dog out while the crate is
being scanned. The dog back in the crate, you place it on a conveyor
belt leading down and out of the building.

The Lufthansa employee will need two documents for company records:
- copy of the passport
- copy of the EU health certificate

If you do not have these copies, they have a copier in their office.
That's it. Go though passport control and enjoy your flight.

* In Europe

Frankfurt Airport is too big to allow travelers access to their
pets. You'll have to wait until your final destination to check on your
animal.

I spotted a small convenient quirk in the rules. The EU regulations
state that the pets do not need veterinary inspection on arrival and
that the papers can be checked either at the port of entry to EU
(Frankfurt) if there is time, or at the final destination (Helsinki).
However, on arrival to Helsinki there was no indication if the papers
had been checked (but they most probably were). Since the second
flight is inside EU, that arrival luggage hall does not have customs
officers permanently. There is a button near the exit that activates
an intercom to the customs. When I imported my dogs (a Finnish
citizen importing to Finland), they were quite uninterested. All they
wanted to know was if the dogs were definitely my own (positive!) and
in that case just go on and leave with the dogs.

