#+TITLE:       Elfeed org
#+AUTHOR:      Heikki Lehvaslaiho
#+EMAIL:       heikki.lehvaslaiho@gmail.com
#+DATE:        2015-02-26 Thu
#+URI:         /blog/%y/%m/%d/elfeed-org
#+KEYWORDS:    elfeed
#+TAGS:        emacs
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: MOre uses for org mode

While I was at it, I moved my feed list into an org file
using elfeed-org.

* Elfeed-org

Elfeed-org reads simple hierarchical org file =~/.emacs.org= that
lists all the feed URLs under first lever header Blogs that has a
property ID with value elfeed. Header under that have a tags that are
inherited by lower headers. I have not found use to the inheritance
with my small number of feeds.

#+BEGIN_EXAMPLE
#+STARTUP: indent
* Blogs
:PROPERTIES:
 :ID: elfeed
 :END:
** Daily News                                                             :n:
*** http://feeds.bbci.co.uk/news/science_and_environment/rss.xml
*** http://feeds.bbci.co.uk/news/world/rss.xml
*** http://feeds.bbci.co.uk/news/technology/rss.xml
*** http://feeds.bbci.co.uk/news/health/rss.xml
*** http://www.bbc.com/culture/feed.rss
** News in Science Journals                                               :j:
*** http://feeds.nature.com/NatureNewsComment?format=xml
*** http://news.sciencemag.org/rss/weekly_news_email.xml
*** http://feeds.newscientist.com/science-news
...
#+END_EXAMPLE

The above extract shows the two most common categories of my feeds:
daily news (n) and science news (j). Both have dozens of articles
daily. The rest of the feeds have  a few articles a day or are not
updated daily. I have memorized the one letter category tags so I do
not have any need to change them.

Elfeed knows to use this org file by adding one line in the emacs
configuration.

#+BEGIN_SRC emacs-lisp
     (require 'org-page)
#+END_SRC

