#+TITLE:       Weekend woes
#+AUTHOR:      Heikki Lehväslaiho
#+EMAIL:       heikki.lehvaslaiho@gmail.com
#+DATE:        2015-03-28 Sat
#+URI:         /blog/%y/%m/%d/weekend-woes
#+KEYWORDS:    saudi arabia, calender, weekend, habits, expat
#+TAGS:        saudi
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: How changing definition of weekend messes you up

One special aspect of expat life in Saudi Arabia that has unexpectedly
profound effect on your life is its weekend. It is not where you'd
expect to find it, from Saturday to Sunday.

We all realize that while some things in our life and environment are
constant and some change depending on country, geography, or time of
the year. It is changes in those unchanging things that you have grown
up with that have the most subtle and profound effect on your daily
life.

The effect is bit like going to Great Britain for the first time after
a lifetime of driving your car on the right side of the road: Unless
you have thought it through beforehand, you'll drive to the first
junction, try to turn right and your mind will draw a complete blank
trying to figure out what you'll have to do to get to the correct lane.
You can not expect such a small change to have such a big impact.

For decades, the Saudi Arabian weekend was from Thursday to Friday.
The workweek used to begin on Saturday when rest of the world started
their weekend. For expats in Saudi Arabia, this meant that the first
couple of days of the workweek ware blissfully quiet. On the other
hand, if you not only communicated with the outside world, but
depended on it, you ended up working continuously without hardly any
break at all.

The shift to the Saudi weekend did not go smoothly. It took years of
practice not to be confused when your friend started talking about
organizing a BBQ on Saturday afternoon, when he actually meant
Thursday. Similarly, your collaeque would try to catch up with
something during the weekend and suggest that you continue discussing
it on Monday -- and you are supposed to automatically know she meant
Saturday, the first day of the workweek. And the day in the middle of
the workweek is called ... naturally Monday. We've laughed so many
good laughs over these harmless stumbles of thought.

Once the busy expat had got used to all that, the rug was figuratively
swept under his feet: On 25 of June in 2013, a royal degree ordered
the country to follow the suit of the other Arab Gulf countries and
move to Friday-Saturday weekend. The degree came without warning and
was effective immediately. A mad scramble ensued to figure out how
everything works and fix calendars. The ensuing weekend was three days
long to catch up.

The good news about the change was that Saudi Arabia is now out of
sync with most of the world by only one day, and aligned with most
other Arab countries in the region that have been following this
custom for years. Now, the only two countries in the world left using
the Thursday-Friday weekend are Afganistan and Yemen. They definitely
form a club no-one wants to be part of.

At more personal level, this meant that you were doubly confused. The
weekend now has its "Sunday" first and it is followed by the less holy
"Saturday". So, your "Saturday" that used to be Thursday is again
Saturday. If you have waited for the whole week to go for
uninterrupted late night shopping (after the last prayed call of the
day that closes all the shops), you better do it all on Thursday,
because staying up late on Saturday is not going to help you getting
up early to work on Sunday morning.

If this is not confusing enough, you could always try working and
living at the Sultanate of Brunei. It is unique place on earth in
having a non-contiguous weekend consisting of Friday and Sunday
with a workday Saturday in-between.

