#+TITLE:       Weekend woes
#+AUTHOR:      Heikki Lehväslaiho
#+EMAIL:       heikki.lehvaslaiho@gmail.com
#+DATE:        2015-03-28 Sat
#+URI:         /blog/%y/%m/%d/weekend-woes
#+KEYWORDS:    saudi arabia, calender, weekend, habbits
#+TAGS:        saudi
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: How changeing definition of weekend messes you up

One of the unexpectedly profound special aspects of life in Saudi
Arabia was its weekend. It is not where you'd expect to find it,
Saturday and Sunday. It is bit like going to Great Britain for the
first time after a lifetime of driving your car on the right side of
the road. You can not expect such a small change to have such a big
impact.

We all realize that some things in our surroundings are constant and
some change depending on country, geography, or time of the year. It
is those things that you have grown to expect to remain the same all
the time, that have the most subtle and profound effect on your daily
life.

For decades, the Saudi Arabian weekend was from Thursday to Friday.
The work week begins on Saturday when rest of the world starts their
weekend. For expats in Saudi Arabia, this meant that the first couple
of days of the workweek ware blissfully quiet. Of course, if you not
only communicated with the outside world, but depended on is, you
could not take your weekly time off according to local customs: you
ended up working continuously without hardly any break at all.

It took years of practice not to be confused when your friend started
talking about organizing a BBQ on the Saturday afternoon, when he
actually meant Thursday. Similarly, your collaeque would try to catch
up with something during the weekend and suggest that you continue
discussing it on Monday -- and you are supposed to automatically know
she meant Saturday. And the day middle of the workweek is called ...
naturally Monday. We've laughed so many good laughs over these
harmless stumbles of thought.

Once the busy expat got used to all that, the rug was figuratively
swept under his feet: 25 of June in 2013 the royal degree ordered the
country to follow the suit of the other Arab Gulf countries and move
to Friday-Saturday weekend. Mad scramble ensued. The following weekend
was a three days long to catch up and the new rule is in place from
there on.

The good news is that Saudi Arabia is now out of sync with most of the
world by one day, only, and aligned with most other countries in the
region. The only two countries in the world left in the
Thursday-Friday weekend are Afganistan and Yemen. They definitely form
a club no-one wants to be part of.

At more personal level, this means that the weekend now has "Sunday"
first and it is followed by the less holy "Saturday". So, your
Saturday that used to be called Thursday is again Saturday. If you
have waited for the whole week to go for uninterrupted late night
shopping, you better do it all on Thursday, because staying up late on
Saturday is not going to help you getting up early to work on Sunday
morning.

If this is not confusing enough, you could always try working at the
Sultanate of Brunei. It is unique place on earth in having a
non-contiguous "weekend", consisting of Friday and Sunday.

